### ISSUE TITLE
java.lang.IllegalStateException: Toolkit not initialized

### ISSUE THREAD

**Issue by Wikbake** [PreCyz/GitDiffGenerator#13]
Hey!

When starting application ("11+Gipter_v4.0.5") it throws: 

```2021-05-17 08:47:47 [INFO ] [main] pg.gipter.Main                : Gipter started.
2021-05-17 08:47:47 [INFO ] [main] r.core.UIApplicationProperties: Configuration [] loaded.
2021-05-17 08:47:47 [INFO ] [main] r.core.UIApplicationProperties: Application properties loaded: version='4.0.5', configurationName='', authors='NO_AUTHORS', gitAuthor='', mercurialAuthor='', svnAuthor='', committerEmail='', itemPath='NO_ITEM_PATH\2021-may-week-21.txt', fileName='2021-may-week-21.txt', projectPath='NO_PROJECT_PATH', periodInDays='7', startDate='2021-05-10', endDate='2021-05-17', uploadType='SIMPLE', skipRemote='true', fetchAll='true', deleteDownloadedFiles='true', preferredArgSource='CLI', useUI='true', silentMode='false', enableOnStartup='true', upgradeFinished='false', loggerLevel='INFO', checkLastItemEnabled='true', checkLastItemCronExpression='0 5 12 20 * ?', toolkitCredentialsSet='false', toolkitUsername='UNKNOWN_USER', toolkitUrl='https://goto.netcompany.com', toolkitWSUrl='https://goto.netcompany.com/cases/GTE106/NCSCOPY/_vti_bin/lists.asmx', toolkitDomain='NCDMZ', toolkitCopyListName='WorkItems', toolkitUserFolder='https://goto.netcompany.com/cases/GTE106/NCSCOPY/Lists/WorkItems/UNKNOWN_USER', toolkitProjectListNames='Deliverables'.
2021-05-17 08:47:47 [INFO ] [main] pg.gipter.Main                : Level of the logger [org.springframework] is set to [INFO]
2021-05-17 08:47:47 [INFO ] [main] pg.gipter.Main                : Level of the logger [org.mongodb] is set to [INFO]
2021-05-17 08:47:47 [INFO ] [main] pg.gipter.Main                : Level of the logger [pg.gipter] is set to [INFO]
2021-05-17 08:47:47 [INFO ] [main] pg.gipter.Main                : Level of the logger [org.quartz] is set to [INFO]
2021-05-17 08:47:47 [INFO ] [main] pg.gipter.Main                : Version of application '4.0.5'.
2021-05-17 08:47:47 [INFO ] [main] pg.gipter.Main                : Gipter can use '8' threads.
2021-05-17 08:47:47 [INFO ] [main] r.converters.ItemTypeConverter: There is nothing to convert.
2021-05-17 08:47:47 [INFO ] [main] r.converters.SecurityConverter: Security file detected.
2021-05-17 08:47:47 [WARN ] [main] onverters.ProgramDataConverter: Error when loading data.properties. Exception message is: data.properties (The system cannot find the file specified)
2021-05-17 08:47:47 [INFO ] [main] onverters.ProgramDataConverter: No data.properties to convert
Exception in thread "main" java.lang.ExceptionInInitializerError
        at pg.gipter.ui.alerts.WebViewService.getInstance(WebViewService.java:65)
        at pg.gipter.Main.main(Main.java:40)
        at pg.gipter.Java11Main.main(Java11Main.java:6)
Caused by: java.lang.IllegalStateException: Toolkit not initialized
        at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:410)
        at com.sun.javafx.application.PlatformImpl.runLater(PlatformImpl.java:405)
        at javafx.application.Platform.runLater(Platform.java:150)
        at pg.gipter.ui.alerts.WebViewService.init(WebViewService.java:43)
        at pg.gipter.ui.alerts.WebViewService$WebViewServiceHolder.<clinit>(WebViewService.java:29)
        ... 3 more```

**Comment by Wikbake** [comment]
Probably I was just missing 11 version of the JFX.

**Comment by PreCyz** [comment]
Usually this kind of exception appears for Java 11 when you want to run application from IDE (or cmd) not having JavaFX lib set as run argument. You must specifically set the path to the JavaFX modules that you want to use when you run the application. This is described in the [Gipter from CLI -> java -jar for 11+ distribution in Wiki](https://github.com/PreCyz/GitDiffGenerator/wiki/Gipter-from-CLI#java--jar-for-11-distribution).

If you use `mvn clean package` command it will build fat jar that can be run by double click or simply `java -jar Gipter.jar` from cmd.
